version: '3.8'

services:
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: 'todo'
      POSTGRES_USER: 'root'
      POSTGRES_PASSWORD: 'password'
    ports:
      - "5432:5432"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql